export const Data = [
  {
    id : 1,
    category: "cloths",
    brand: "H&M",
    title: "Top kurti for girl trending design",
    price: 8889,
    discount: 25,
    rating: 177,
    description:
      "Blue longline empire top Ethnic motifs print Mandarin collar three quarter, cuffed sleevesGathered or pleated detailWoven cotton",
    image: require("./Image/man/kurti/1kurti.avif"),
    image1: require("./Image/man/kurti/2kurti.avif"),
    image2: require("./Image/man/kurti/3kurti.webp"),
    image3: require("./Image/man/kurti/4kurti.avif"),
  },
  {
    id : 2,
    category: "cloths",
    brand: "Puma",
    title: "Puma Mans Primum Jacket",
    price: 6669,
    discount: 30,
    rating: 177,
    description: "Men Solid Wedding Blazer",
    image: require("./Image/man/puma jacket/1man.webp"),
    image1: require("./Image/man/puma jacket/2puma.jpg"),
    image2: require("./Image/man/puma jacket/3puma.jpg"),
    image3: require("./Image/man/puma jacket/2puma.jpg"),
  },
  {
    id : 3,
    category: "cloths",
    title: "Drop Dead Gorgeous Cocktail Dress",
    brand: "Tomholend",
    discount: 23,
    rating: 177,
    price: 9999,
    description: "Breasted Formal, Wedding Blazer",
    image: require("./Image/man/redgirl/1redgirl.avif"),
    image1: require("./Image/man/redgirl/2redgirl.avif"),
    image2: require("./Image/man/redgirl/3redgirll.avif"),
    image3: require("./Image/man/redgirl/4redgirl.avif"),
  },

  {
    id : 4,
    category: "cloths",
    brand: "Calvin calin",
    title: "Girl Top Short Jacket",
    price: 5559,
    discount: 20,
    rating: 177,

    description: "Men Self Design Bandhgala Festive Blazer  (Maroon)",
    image: require("./Image/man/jackit girl/1jackit.webp"),
    image1: require("./Image/man/jackit girl/2jackit.jpg"),
    image2: require("./Image/man/jackit girl/3jackit.jpg"),
    image3: require("./Image/man/jackit girl/4jackit.jpg"),
  },

  {
    id : 5,
    category: "cloths",
    title: "Girl Denim Top With Scrart",
    brand: "Levis",
    price: 7779,
    discount: 40,
    rating: 177,

    description: "Men Solid Single Breasted Formal, Wedding Blazer",
    image: require("./Image/man/bluegirl/1girl.avif"),
    image1: require("./Image/man/bluegirl/2girl.avif"),
    image2: require("./Image/man/bluegirl/3girl.avif"),
    image3: require("./Image/man/bluegirl/4girl.avif"),
  },

  {
    id : 6,
    category: "cloths",
    brand: "Gucchi",
    title: "Glitter Ruched Wrap Bodycon Dress",
    price: 1119,
    discount: 13,
    rating: 177,

    description: "Men Checkered Single Breasted Formal Blazer  (Dark Blue)",
    image: require("./Image/man/vestarn/1vestern.avif"),
    image1: require("./Image/man/vestarn/2vestern.avif"),
    image2: require("./Image/man/vestarn/3vestern.avif"),
    image3: require("./Image/man/vestarn/4vestern.avif"),
  },

  {
    id : 7,
    category: "cloths",
    brand: "United Colors of Benetton",
    title: "Men Navy Blue Solid Sweatshirt",
    price: 9999,
    description: "Men Solid Single Breasted Formal, Wedding Blazer",
    discount: 10,
    rating: 177,

    image: require("./Image/man/1man.webp"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
  {
    id : 8,
    category: "cloths",
    brand: "Van Husain",

    title: "Man Prmium shirt",
    price: 9999,
    discount: 11,
    rating: 177,

    description: "Men Solid Single Breasted Formal, Wedding Blazer",
    image: require("./Image/man/9.jpg"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
  {
    id : 9,
    category: "Shoes",
    brand: "Nike",

    title: "Downshifter 13 Running Shoes",
    price: 9999,
    discount: 11,
    rating: 177,

    description: "Men Solid Single Breasted Formal, Wedding Blazer",
    image: require("./Image/shoes/nikeblack/1nike.avif"),
    image1: require("./Image/shoes/nikeblack/2black.avif"),
    image2: require("./Image/shoes/nikeblack/3black.avif"),
    image3: require("./Image/shoes/nikeblack/4black.avif"),
  },
  {
    id : 10,
    category: "Shoes",
    title: "Downshifter 11 Running Shoes",
    brand: "Nike",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/shoes/nikewblue/1nikewblue.avif"),
    image1: require("./Image/shoes/nikewblue/2nikewblue.avif"),
    image2: require("./Image/shoes/nikewblue/3nikewblue.avif"),
    image3: require("./Image/shoes/nikewblue/4nikewblue.avif"),
  },
  {
    id : 11,
    category: "Shoes",
    title: "Downshifter 11 Running Shoes",
    brand: "Nike",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/shoes/nikeyellow/1nikeyellow.avif"),
    image1: require("./Image/shoes/nikegreen/2nikegreen.avif"),
    image2: require("./Image/shoes/nikegreen/3nikegreen.avif"),
    image3: require("./Image/shoes/nikegreen/4nikegreen.avif"),
  },
  {
    id : 12,
    category: "Shoes",
    title: "Downshifter 11 Running Shoes",
    brand: "Nike",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/shoes/nikegreen/1nikegreen.avif"),
    image1: require("./Image/shoes/nikeyellow/2nikeyellow.avif"),
    image2: require("./Image/shoes/nikeyellow/3nikeyellow.avif"),
    image3: require("./Image/shoes/nikeyellow/4nikeyellow.avif"),
  },
  {
    id : 13,
    category: "accessories",
    title: "Bose primuium headphone",
    brand: "bose",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/acces/2bose headphone.jpg"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
  {
    id : 14,
    category: "accessories",
    title: "Apple Watch Ultre",
    brand: "APPLE",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/acces/1apple watch.jpg"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
  {
    id : 15,
    category: "accessories",
    title: "Oneplus buds pro",
    brand: "ONEPLUS",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/acces/3oneplus.avif"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
  {
    id : 16,
    category: "accessories",
    title: "Realme buds air 2",
    brand: "REALME",

    price: 9999,
    discount: 25,
    rating: 177,

    description: "Formal, Wedding Blazer",
    image: require("./Image/acces/4realme.avif"),
    image1: require("./Image/man/1man.webp"),
    image2: require("./Image/man/1man.webp"),
    image3: require("./Image/man/1man.webp"),
  },
];
